import type { Property } from '../types/property';
import { DEFAULT_ORGANIZATION } from '../types/organization';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-585',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'INM-585',
    title: 'Apartamento en Laureles',
    description: 'Cómodo y amplio apartamento ubicado en el sector de Laureles, Medellín. Cuenta con 3 habitaciones, 2 baños, sala-comedor, balcón y cocina integral. Sector residencial tranquilo cerca a parques y vías principales.',
    type: 'apartamento',
    operation: 'arriendo',
    municipality: 'Medellín',
    zone: 'Laureles',
    internalAddress: 'Circular 4 # 71-20, Laureles, Medellín',
    priceCOP: 2000000,
    adminFeeCOP: 250000,
    areaM2: 95,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    stratum: 4,
    features: ['Balcón', 'Cocina Integral', 'Zona de Ropas', 'Ascensor', 'Portería 24 Horas'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: true,
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-21T12:00:00Z',
  },
  {
    id: 'prop-001',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'APT-101',
    title: 'Exclusivo Apartamento con Vista Panorámica en El Poblado',
    description: 'Impresionante apartamento moderno ubicado en sector campestre de Castropol, El Poblado. Cuenta con acabados en mármol italiano, cocina tipo isla abierta, balcón de 25m2 con vista despejada al valle, 3 habitaciones con baño privado, cuarto de servicio y 2 parqueaderos paralelos.',
    type: 'apartamento',
    operation: 'compra',
    municipality: 'Medellín',
    zone: 'El Poblado',
    internalAddress: 'Cra 32 # 10-45, Torre Mirador, Apto 1402 (Propietario: Dr. Rodrigo Valencia - Cel 3105559988)',
    priceCOP: 980000000,
    adminFeeCOP: 650000,
    areaM2: 145,
    bedrooms: 3,
    bathrooms: 4,
    parkingSpots: 2,
    stratum: 6,
    features: ['Piscina Climatizada', 'Gimnasio Dotado', 'Balcón Panorámico', 'Ascensor Privado', 'Seguridad 24/7', 'Turco/Sauna', 'Parqueadero Visitantes'],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: true,
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-18T14:30:00Z',
  },
  {
    id: 'prop-002',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'CAS-204',
    title: 'Casa Campestre en Unidad Cerrada con Bosque Nativo',
    description: 'Hermosa casa independiente en Envigado, sector Loma de las Brujas. Amplio jardín privado, zona BBQ, jacuzzi exterior, sala con doble altura, chimenea a gas, cocina de diseñador y paneles solares instalados.',
    type: 'casa',
    operation: 'compra',
    municipality: 'Envigado',
    zone: 'Loma de las Brujas',
    internalAddress: 'Calle 38 Sur # 25-110, Condominio Bosque Real, Casa 8 (Llaves en portería)',
    priceCOP: 1650000000,
    adminFeeCOP: 820000,
    areaM2: 320,
    bedrooms: 4,
    bathrooms: 5,
    parkingSpots: 4,
    stratum: 5,
    features: ['Jardín Privado', 'Zona BBQ', 'Jacuzzi', 'Senderos Ecológicos', 'Seguridad 24/7', 'Paneles Solares', 'Pet Friendly'],
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'David Ramírez',
    featured: true,
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-19T09:00:00Z',
  },
  {
    id: 'prop-003',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'APT-305',
    title: 'Apartaestudio Moderno Amoblado en Laureles',
    description: 'Excelente apartaestudio ubicado en el corazón gastronómico de Laureles. Completamente dotado con acabados industriales, aire acondicionado, balcón exterior, zona de ropas independiente y parqueadero cubierto.',
    type: 'apartamento',
    operation: 'arriendo',
    municipality: 'Medellín',
    zone: 'Laureles',
    internalAddress: 'Circular 73 # 39B-18, Edificio Concept Laureles, Apto 502',
    priceCOP: 3600000,
    adminFeeCOP: 320000,
    areaM2: 58,
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 1,
    stratum: 5,
    features: ['Amoblado', 'Aire Acondicionado', 'Balcón', 'Ascensor', 'Coworking', 'Rooftop con Terraza'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'David Ramírez',
    featured: false,
    createdAt: '2026-09-10T15:00:00Z',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'prop-004',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'PEN-402',
    title: 'Penthouse Duplex de Lujo en Rosales / Chapinero',
    description: 'Penthouse dúplex exclusivo en los Cerros Orientales de Bogotá. Altura libre de 3 metros, chimenea tradicional, terraza de 45m2 con vista a toda la ciudad, ascensor directo al piso y 3 garajes independientes.',
    type: 'penthouse',
    operation: 'compra',
    municipality: 'Bogotá',
    zone: 'Chapinero / Rosales',
    internalAddress: 'Cra 2 # 78-40, Edificio Los Cerros, PH 10 (Contacto: Inversiones Los Andes)',
    priceCOP: 2400000000,
    adminFeeCOP: 1450000,
    areaM2: 260,
    bedrooms: 3,
    bathrooms: 4,
    parkingSpots: 3,
    stratum: 6,
    features: ['Terraza Privada', 'Vista a la Ciudad', 'Chimenea', 'Ascensor Directo', 'Gimnasio', 'Planta Eléctrica Total'],
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: true,
    createdAt: '2026-09-12T08:30:00Z',
    updatedAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'prop-005',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'OFI-510',
    title: 'Oficina Corporativa en Edificio Inteligente',
    description: 'Piso de oficinas completamente adecuado con salas de juntas, cableado estructurado Cat 6A, control de acceso biométrico, cafetería dotada y 4 parqueaderos. Ubicación premium cerca al metro y centros empresariales.',
    type: 'oficina',
    operation: 'arriendo',
    municipality: 'Medellín',
    zone: 'El Poblado / Milla de Oro',
    internalAddress: 'Cra 43A # 1Sur-100, Torre Empresarial Milla de Oro, Piso 7',
    priceCOP: 12500000,
    adminFeeCOP: 1800000,
    areaM2: 180,
    bedrooms: 0,
    bathrooms: 3,
    parkingSpots: 4,
    stratum: 6,
    features: ['Cableado Estructurado', 'Control Biométrico', 'Salas de Juntas', 'Auditorio Común', 'Seguridad 24/7', 'Batería de Baños'],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: false,
    createdAt: '2026-09-14T09:00:00Z',
    updatedAt: '2026-09-19T08:00:00Z',
  },
  {
    id: 'prop-006',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'APT-608',
    title: 'Apartamento Familiar Cerca a Parque Sabaneta',
    description: 'Excelente apartamento de 3 alcobas en unidad residencial completa de Sabaneta. Cerca a colegios, centros comerciales y transporte público. Balcón sin poniente, parqueadero cubierto y cuarto útil.',
    type: 'apartamento',
    operation: 'arriendo',
    municipality: 'Sabaneta',
    zone: 'Sector Las Lomitas',
    internalAddress: 'Calle 75 Sur # 43A-30, Urbanización Vivero Club, Apto 804',
    priceCOP: 2900000,
    adminFeeCOP: 260000,
    areaM2: 78,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    stratum: 4,
    features: ['Piscina', 'Cancha Múltiple', 'Zona Infantil', 'Salón Social', 'Balcón', 'Parqueadero Cubierto'],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'David Ramírez',
    featured: false,
    createdAt: '2026-09-15T14:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z',
  },
  {
    id: 'prop-007',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'LOC-702',
    title: 'Local Comercial en Plazoleta Gastronómica',
    description: 'Local esquinero de alto tráfico peatonal y vehicular con vitrina panorámica de 12 metros. Cuenta con trampa de grasas, punto de gas comercial y terraza exterior para mesas.',
    type: 'local',
    operation: 'arriendo',
    municipality: 'Bogotá',
    zone: 'Usaquén',
    internalAddress: 'Cra 6 # 118-24, Local 3, Usaquén Centro Histórico',
    priceCOP: 8500000,
    adminFeeCOP: 950000,
    areaM2: 110,
    bedrooms: 0,
    bathrooms: 2,
    parkingSpots: 0,
    stratum: 5,
    features: ['Gas Comercial', 'Trampa de Grasas', 'Vitrina Esquinera', 'Terraza Exterior', 'Alto Flujo Peatonal'],
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: false,
    createdAt: '2026-09-16T11:00:00Z',
    updatedAt: '2026-09-19T07:30:00Z',
  },
  {
    id: 'prop-008',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'APT-802',
    title: 'Apartamento de 2 Habitaciones en Belén La Palma',
    description: 'Hermoso apartamento de 2 alcobas y 2 baños completos en Belén La Palma, Medellín. Cuenta con cocina integral, piso en porcelanato, balcón iluminado, parqueadero privado y portería 24 horas. Cerca al Parque de Belén y estaciones de Metroplús.',
    type: 'apartamento',
    operation: 'arriendo',
    municipality: 'Medellín',
    zone: 'Belén',
    internalAddress: 'Calle 30A # 76-42, Edificio Belén Real, Apto 802 (Propietario: Sra. Amparo Ríos)',
    priceCOP: 2350000,
    adminFeeCOP: 210000,
    areaM2: 64,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    stratum: 4,
    features: ['Balcón', 'Ascensor', 'Seguridad 24/7', 'Parqueadero Cubierto', 'Gas Natural'],
    images: [
      'https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'David Ramírez',
    featured: true,
    createdAt: '2026-09-16T14:00:00Z',
    updatedAt: '2026-09-19T10:00:00Z',
  },
  {
    id: 'prop-009',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'APT-901',
    title: 'Apartamento 2 Alcobas Moderno en Laureles Nogal',
    description: 'Apartamento de 2 habitaciones en sector residencial tranquilo de Laureles Nogal. Cocina abierta con barra americana, balcón con vista arbolada, vestier en alcoba principal y parqueadero privado.',
    type: 'apartamento',
    operation: 'arriendo',
    municipality: 'Medellín',
    zone: 'Laureles',
    internalAddress: 'Transversal 39B # 74-12, Edificio Nogales 74, Apto 901',
    priceCOP: 2500000,
    adminFeeCOP: 240000,
    areaM2: 68,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    stratum: 5,
    features: ['Balcón', 'Ascensor', 'Seguridad 24/7', 'Parqueadero Cubierto', 'Zona de Ropas'],
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: true,
    createdAt: '2026-09-17T09:30:00Z',
    updatedAt: '2026-09-19T11:00:00Z',
  },
  {
    id: 'prop-010',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'CAS-1003',
    title: 'Casa en Conjunto Cerrado en Chicó Norte',
    description: 'Casa clásica remodelada en el prestigioso sector de Chicó Norte, Bogotá. 3 niveles, patio interior privado, chimenea a leña, estudio independiente, 4 alcobas y 3 parqueaderos.',
    type: 'casa',
    operation: 'compra',
    municipality: 'Bogotá',
    zone: 'Chicó',
    internalAddress: 'Cra 14 # 96-30, Condominio El Virrey, Casa 3',
    priceCOP: 2150000000,
    adminFeeCOP: 1100000,
    areaM2: 280,
    bedrooms: 4,
    bathrooms: 4,
    parkingSpots: 3,
    stratum: 6,
    features: ['Jardín Privado', 'Chimenea', 'Estudio', 'Seguridad 24/7', 'Cámaras de Seguridad'],
    images: [
      'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'Laura Gómez',
    featured: false,
    createdAt: '2026-09-17T16:00:00Z',
    updatedAt: '2026-09-19T08:30:00Z',
  },
  {
    id: 'prop-011',
    organizationId: DEFAULT_ORGANIZATION.id,
    code: 'FIN-1102',
    title: 'Finca Campestre con Piscina y Cancha en Rionegro',
    description: 'Espectacular finca de recreo y descanso en Rionegro, sector Llanogrande. Casa principal de 350m2, quiosco BBQ, piscina climatizada, árboles frutales y portón eléctrico.',
    type: 'finca',
    operation: 'compra',
    municipality: 'Rionegro',
    zone: 'Llanogrande',
    internalAddress: 'Vereda El Tablazo, Km 4 Vía Llanogrande, Finca Los Guayacanes',
    priceCOP: 3200000000,
    adminFeeCOP: 450000,
    areaM2: 4500,
    bedrooms: 5,
    bathrooms: 6,
    parkingSpots: 6,
    stratum: 5,
    features: ['Piscina Climatizada', 'Zona BBQ', 'Jardín Privado', 'Jacuzzi', 'Cancha Múltiple', 'Pet Friendly'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    ],
    status: 'disponible',
    assignedAgent: 'David Ramírez',
    featured: true,
    createdAt: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-19T09:15:00Z',
  }
];
