import type { Lead } from '../types/lead';
import { DEFAULT_ORGANIZATION } from '../types/organization';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    organizationId: DEFAULT_ORGANIZATION.id,
    name: 'Carlos Andrés Mendoza',
    phone: '+57 312 456 7890',
    email: 'carlos.mendoza@inversiones.com',
    operationType: 'compra',
    propertyType: 'apartamento',
    municipality: 'Medellín',
    zone: 'El Poblado',
    budget: 980000000,
    minBudget: 800000000,
    maxBudget: 1100000000,
    currency: 'COP',
    desiredFeatures: ['Balcón Panorámico', 'Piscina Climatizada', '2 Parqueaderos'],
    interestedPropertyIds: ['prop-001'],
    notes: 'Busca apartamento de 3 habitaciones con vista panorámica, parqueadero doble y acabados de lujo.',
    status: 'visita_agendada',
    priority: 'alto',
    source: 'web_form',
    assignedAgent: 'Laura Gómez',
    consentHabeasData: true,
    activities: [
      {
        id: 'act-1-1',
        type: 'created',
        description: 'Prospecto captado desde formulario web de campaña Poblado.',
        createdAt: '2026-09-15T10:30:00Z',
        author: 'Sistema',
      },
      {
        id: 'act-1-2',
        type: 'contact_attempt',
        description: 'Llamada inicial realizada. Muy interesado en el inmueble APT-101.',
        createdAt: '2026-09-15T14:20:00Z',
        author: 'Laura Gómez',
      },
      {
        id: 'act-1-3',
        type: 'visit_scheduled',
        description: 'Visita programada para el viernes 25 de septiembre a las 3:00 PM con el propietario.',
        createdAt: '2026-09-18T16:00:00Z',
        author: 'Laura Gómez',
      },
    ],
    createdAt: '2026-09-15T10:30:00Z',
    updatedAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'lead-2',
    organizationId: DEFAULT_ORGANIZATION.id,
    name: 'Valentina Restrepo',
    phone: '+57 300 892 1144',
    email: 'valentina.restrepo@designstudio.co',
    operationType: 'arriendo',
    propertyType: 'apartamento',
    municipality: 'Medellín',
    zone: 'Laureles',
    budget: 3600000,
    minBudget: 3000000,
    maxBudget: 4000000,
    currency: 'COP',
    desiredFeatures: ['Amoblado', 'Balcón', 'Ascensor'],
    interestedPropertyIds: ['prop-003'],
    notes: 'Diseñadora gráfica requiere apartaestudio amoblado en Laureles con excelente luz y balcón.',
    status: 'interesado',
    priority: 'medio',
    source: 'asistente_ia',
    assignedAgent: 'David Ramírez',
    consentHabeasData: true,
    activities: [
      {
        id: 'act-2-1',
        type: 'created',
        description: 'Captado por el Asistente Web IA interactuando sobre el inmueble APT-305.',
        createdAt: '2026-09-16T09:15:00Z',
        author: 'SofIA Asistente',
      },
      {
        id: 'act-2-2',
        type: 'note_added',
        description: 'Se enviaron fotos adicionales por WhatsApp y ficha técnica.',
        createdAt: '2026-09-17T11:00:00Z',
        author: 'David Ramírez',
      },
    ],
    createdAt: '2026-09-16T09:15:00Z',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'lead-3',
    organizationId: DEFAULT_ORGANIZATION.id,
    name: 'Alejandro Morales Villa',
    phone: '+57 318 671 2299',
    email: 'amorales@agrotech.com.co',
    operationType: 'compra',
    propertyType: 'casa',
    municipality: 'Envigado',
    zone: 'Loma de las Brujas',
    budget: 1650000000,
    minBudget: 1400000000,
    maxBudget: 1800000000,
    currency: 'COP',
    desiredFeatures: ['Jardín Privado', 'Zona BBQ', 'Jacuzzi', 'Seguridad 24/7'],
    interestedPropertyIds: ['prop-002'],
    notes: 'Familia con 2 hijos y mascotas. Busca casa campestre en Envigado con amplio jardín y zonas verdes.',
    status: 'negociacion',
    priority: 'alto',
    source: 'portal_inmobiliario',
    assignedAgent: 'Laura Gómez',
    consentHabeasData: true,
    activities: [
      {
        id: 'act-3-1',
        type: 'created',
        description: 'Prospecto importado desde portal Finca Raíz.',
        createdAt: '2026-09-17T15:45:00Z',
        author: 'Sistema',
      },
      {
        id: 'act-3-2',
        type: 'status_change',
        description: 'Presentada oferta económica formal por el inmueble CAS-204.',
        createdAt: '2026-09-18T09:00:00Z',
        author: 'Laura Gómez',
      },
    ],
    createdAt: '2026-09-17T15:45:00Z',
    updatedAt: '2026-09-18T09:00:00Z',
  },
  {
    id: 'lead-4',
    organizationId: DEFAULT_ORGANIZATION.id,
    name: 'Mariana Duque Gómez',
    phone: '+57 311 555 4321',
    email: 'mariana.duque@gmail.com',
    operationType: 'arriendo',
    propertyType: 'apartamento',
    municipality: 'Sabaneta',
    zone: 'Sector Las Lomitas',
    budget: 2900000,
    minBudget: 2500000,
    maxBudget: 3200000,
    currency: 'COP',
    desiredFeatures: ['Piscina', 'Zona Infantil', 'Balcón'],
    interestedPropertyIds: ['prop-006'],
    notes: 'Busca apartamento de 3 alcobas en Sabaneta. Póliza preaprobada con Sura.',
    status: 'nuevo',
    priority: 'alto',
    source: 'asistente_ia',
    assignedAgent: 'David Ramírez',
    consentHabeasData: true,
    activities: [
      {
        id: 'act-4-1',
        type: 'created',
        description: 'Asistente IA capturó solicitud de arrendamiento para APT-608.',
        createdAt: '2026-09-19T08:10:00Z',
        author: 'SofIA Asistente',
      },
    ],
    createdAt: '2026-09-19T08:10:00Z',
    updatedAt: '2026-09-19T08:10:00Z',
  },
  {
    id: 'lead-5',
    organizationId: DEFAULT_ORGANIZATION.id,
    name: 'Inversiones Globales S.A.S.',
    phone: '+57 315 889 0011',
    email: 'jortiz@inversionesglobales.com',
    operationType: 'compra',
    propertyType: 'penthouse',
    municipality: 'Bogotá',
    zone: 'Chapinero / Rosales',
    budget: 2400000000,
    minBudget: 2000000000,
    maxBudget: 2600000000,
    currency: 'COP',
    desiredFeatures: ['Terraza Privada', 'Vista a la Ciudad', 'Ascensor Directo'],
    interestedPropertyIds: ['prop-004'],
    notes: 'Cierre de compra de Penthouse PEN-402 en Rosales.',
    status: 'cerrado',
    priority: 'alto',
    source: 'referido',
    assignedAgent: 'Laura Gómez',
    consentHabeasData: true,
    activities: [
      {
        id: 'act-5-1',
        type: 'created',
        description: 'Contacto directo por referido corporativo.',
        createdAt: '2026-08-20T11:00:00Z',
        author: 'Gerencia',
      },
      {
        id: 'act-5-2',
        type: 'status_change',
        description: 'Firma de promesa de compraventa y pago de arras completado.',
        createdAt: '2026-09-14T17:30:00Z',
        author: 'Laura Gómez',
      },
    ],
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-09-14T17:30:00Z',
  },
  {
    id: 'lead-6',
    organizationId: DEFAULT_ORGANIZATION.id,
    name: 'Esteban Cárdenas',
    phone: '+57 320 123 9988',
    email: 'esteban.cardenas@outlook.com',
    operationType: 'arriendo',
    propertyType: 'apartamento',
    municipality: 'Medellín',
    zone: 'Belen',
    budget: 1800000,
    currency: 'COP',
    notes: 'Presupuesto por debajo de la oferta disponible en la zona deseada.',
    status: 'no_interesado',
    priority: 'bajo',
    source: 'web_form',
    assignedAgent: 'David Ramírez',
    consentHabeasData: true,
    activities: [
      {
        id: 'act-6-1',
        type: 'created',
        description: 'Registro desde formulario general.',
        createdAt: '2026-09-10T14:00:00Z',
        author: 'Sistema',
      },
    ],
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-12T16:30:00Z',
  },
];
